-- 陶艺培训班管理系统 MySQL 8.3 建表脚本
-- 生成时间: 2026-03-07

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `ty_cloud`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE `ty_cloud`;

/* ------------------------------
   1. 系统与权限
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_sys_campus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_code` VARCHAR(64) NOT NULL,
  `campus_name` VARCHAR(128) NOT NULL,
  `contact_name` VARCHAR(64) DEFAULT NULL,
  `contact_phone` VARCHAR(32) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_sys_campus_code` (`campus_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_sys_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `username` VARCHAR(64) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `real_name` VARCHAR(64) NOT NULL,
  `mobile` VARCHAR(32) DEFAULT NULL,
  `email` VARCHAR(128) DEFAULT NULL,
  `job_no` VARCHAR(64) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `last_login_time` DATETIME DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_sys_user_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_sys_role` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `role_code` VARCHAR(64) NOT NULL,
  `role_name` VARCHAR(128) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `remark` VARCHAR(500) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_sys_role_code` (`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_sys_user_role` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `role_id` BIGINT UNSIGNED NOT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_sys_user_role` (`user_id`, `role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_sys_menu` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `menu_name` VARCHAR(128) NOT NULL,
  `menu_type` TINYINT NOT NULL,
  `route_path` VARCHAR(255) DEFAULT NULL,
  `component` VARCHAR(255) DEFAULT NULL,
  `perms` VARCHAR(255) DEFAULT NULL,
  `icon` VARCHAR(100) DEFAULT NULL,
  `sort_no` INT NOT NULL DEFAULT 0,
  `visible` TINYINT NOT NULL DEFAULT 1,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_sys_role_menu` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `role_id` BIGINT UNSIGNED NOT NULL,
  `menu_id` BIGINT UNSIGNED NOT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_sys_role_menu` (`role_id`, `menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_sys_operation_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `module` VARCHAR(100) NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `request_uri` VARCHAR(255) DEFAULT NULL,
  `request_method` VARCHAR(16) DEFAULT NULL,
  `request_params` TEXT,
  `ip` VARCHAR(64) DEFAULT NULL,
  `result_code` VARCHAR(32) DEFAULT NULL,
  `cost_ms` BIGINT DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/* ------------------------------
   2. 招生与学员
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_crm_channel` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `channel_code` VARCHAR(64) NOT NULL,
  `channel_name` VARCHAR(128) NOT NULL,
  `channel_type` VARCHAR(64) DEFAULT NULL,
  `owner_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_crm_channel_code` (`channel_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_crm_lead` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `lead_name` VARCHAR(64) NOT NULL,
  `mobile` VARCHAR(32) DEFAULT NULL,
  `gender` TINYINT DEFAULT NULL,
  `age` INT DEFAULT NULL,
  `source_channel_id` BIGINT UNSIGNED DEFAULT NULL,
  `intent_level` TINYINT DEFAULT NULL,
  `interested_course` VARCHAR(255) DEFAULT NULL,
  `owner_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `next_follow_time` DATETIME DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_crm_lead_follow` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `lead_id` BIGINT UNSIGNED NOT NULL,
  `follow_type` VARCHAR(64) DEFAULT NULL,
  `content` VARCHAR(2000) DEFAULT NULL,
  `follow_time` DATETIME NOT NULL,
  `next_follow_time` DATETIME DEFAULT NULL,
  `follower_id` BIGINT UNSIGNED DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_stu_student` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `student_no` VARCHAR(64) NOT NULL,
  `student_name` VARCHAR(64) NOT NULL,
  `gender` TINYINT DEFAULT NULL,
  `birthday` DATE DEFAULT NULL,
  `mobile` VARCHAR(32) DEFAULT NULL,
  `school` VARCHAR(128) DEFAULT NULL,
  `level` VARCHAR(64) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `first_enroll_time` DATETIME DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_stu_student_no` (`student_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_stu_guardian` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `guardian_name` VARCHAR(64) NOT NULL,
  `relation_type` VARCHAR(32) DEFAULT NULL,
  `mobile` VARCHAR(32) DEFAULT NULL,
  `wechat` VARCHAR(64) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_stu_student_guardian` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `guardian_id` BIGINT UNSIGNED NOT NULL,
  `is_primary_contact` TINYINT(1) NOT NULL DEFAULT 0,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_stu_student_guardian` (`student_id`, `guardian_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_stu_tag` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `tag_name` VARCHAR(64) NOT NULL,
  `tag_type` VARCHAR(64) DEFAULT NULL,
  `color` VARCHAR(32) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_stu_tag_name_type` (`tag_name`, `tag_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_stu_student_tag` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `tag_id` BIGINT UNSIGNED NOT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_stu_student_tag` (`student_id`, `tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/* ------------------------------
   3. 课程与排课
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_edu_course` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `course_code` VARCHAR(64) NOT NULL,
  `course_name` VARCHAR(128) NOT NULL,
  `craft_type` VARCHAR(64) DEFAULT NULL,
  `difficulty_level` VARCHAR(32) DEFAULT NULL,
  `lesson_duration_min` INT NOT NULL,
  `standard_price` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `status` TINYINT NOT NULL DEFAULT 1,
  `description` VARCHAR(1000) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_edu_course_code` (`course_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_edu_course_package` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `package_code` VARCHAR(64) NOT NULL,
  `package_name` VARCHAR(128) NOT NULL,
  `course_id` BIGINT UNSIGNED NOT NULL,
  `total_lessons` INT NOT NULL,
  `gift_lessons` INT NOT NULL DEFAULT 0,
  `valid_days` INT NOT NULL DEFAULT 365,
  `sale_price` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_edu_course_package_code` (`package_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_edu_class` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `class_code` VARCHAR(64) NOT NULL,
  `class_name` VARCHAR(128) NOT NULL,
  `course_id` BIGINT UNSIGNED NOT NULL,
  `teacher_id` BIGINT UNSIGNED DEFAULT NULL,
  `classroom_id` BIGINT UNSIGNED DEFAULT NULL,
  `start_date` DATE DEFAULT NULL,
  `end_date` DATE DEFAULT NULL,
  `max_students` INT NOT NULL DEFAULT 0,
  `class_type` VARCHAR(32) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_edu_class_code` (`class_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_edu_class_student` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `class_id` BIGINT UNSIGNED NOT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `contract_id` BIGINT UNSIGNED DEFAULT NULL,
  `join_date` DATE DEFAULT NULL,
  `leave_date` DATE DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_edu_class_student` (`class_id`, `student_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_edu_lesson` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `class_id` BIGINT UNSIGNED NOT NULL,
  `lesson_no` INT NOT NULL,
  `lesson_date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `teacher_id` BIGINT UNSIGNED DEFAULT NULL,
  `classroom_id` BIGINT UNSIGNED DEFAULT NULL,
  `lesson_topic` VARCHAR(255) DEFAULT NULL,
  `lesson_status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_edu_lesson_class_no` (`class_id`, `lesson_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_res_classroom` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `room_code` VARCHAR(64) NOT NULL,
  `room_name` VARCHAR(128) NOT NULL,
  `capacity` INT NOT NULL DEFAULT 0,
  `location` VARCHAR(255) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_res_classroom_code` (`room_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_res_equipment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `equipment_code` VARCHAR(64) NOT NULL,
  `equipment_name` VARCHAR(128) NOT NULL,
  `equipment_type` VARCHAR(64) DEFAULT NULL,
  `quantity_total` INT NOT NULL DEFAULT 0,
  `quantity_available` INT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_res_equipment_code` (`equipment_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_res_resource_booking` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `resource_type` VARCHAR(32) NOT NULL,
  `resource_id` BIGINT UNSIGNED NOT NULL,
  `lesson_id` BIGINT UNSIGNED DEFAULT NULL,
  `reserve_date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `qty` INT NOT NULL DEFAULT 1,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/* ------------------------------
   4. 报名与财务
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_biz_contract` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `contract_no` VARCHAR(64) NOT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `guardian_id` BIGINT UNSIGNED DEFAULT NULL,
  `package_id` BIGINT UNSIGNED NOT NULL,
  `sign_date` DATE NOT NULL,
  `effective_date` DATE NOT NULL,
  `expire_date` DATE DEFAULT NULL,
  `original_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `receivable_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `paid_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `status` TINYINT NOT NULL DEFAULT 1,
  `salesperson_id` BIGINT UNSIGNED DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_biz_contract_no` (`contract_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_biz_contract_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `contract_id` BIGINT UNSIGNED NOT NULL,
  `course_id` BIGINT UNSIGNED NOT NULL,
  `package_lessons` INT NOT NULL DEFAULT 0,
  `gift_lessons` INT NOT NULL DEFAULT 0,
  `unit_price` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `subtotal_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_fin_order` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `order_no` VARCHAR(64) NOT NULL,
  `business_type` VARCHAR(64) DEFAULT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `contract_id` BIGINT UNSIGNED DEFAULT NULL,
  `order_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `payable_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `due_time` DATETIME DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_fin_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_fin_payment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `payment_no` VARCHAR(64) NOT NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `pay_time` DATETIME NOT NULL,
  `pay_method` VARCHAR(32) NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `transaction_no` VARCHAR(128) DEFAULT NULL,
  `cashier_id` BIGINT UNSIGNED DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_fin_payment_no` (`payment_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_fin_refund` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `refund_no` VARCHAR(64) NOT NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `payment_id` BIGINT UNSIGNED DEFAULT NULL,
  `refund_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `reason` VARCHAR(500) DEFAULT NULL,
  `apply_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `approve_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `refund_time` DATETIME DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_fin_refund_no` (`refund_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_fin_invoice` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `invoice_no` VARCHAR(64) NOT NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `invoice_type` VARCHAR(32) DEFAULT NULL,
  `title` VARCHAR(255) DEFAULT NULL,
  `tax_no` VARCHAR(64) DEFAULT NULL,
  `amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `issue_date` DATE DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_fin_invoice_no` (`invoice_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/* ------------------------------
   5. 上课与消课
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_edu_attendance` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `lesson_id` BIGINT UNSIGNED NOT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `attendance_status` TINYINT NOT NULL,
  `checkin_time` DATETIME DEFAULT NULL,
  `checkout_time` DATETIME DEFAULT NULL,
  `operator_id` BIGINT UNSIGNED DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_edu_attendance` (`lesson_id`, `student_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_edu_leave_request` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `class_id` BIGINT UNSIGNED DEFAULT NULL,
  `lesson_id` BIGINT UNSIGNED DEFAULT NULL,
  `leave_type` VARCHAR(32) DEFAULT NULL,
  `leave_reason` VARCHAR(500) DEFAULT NULL,
  `apply_time` DATETIME NOT NULL,
  `approve_status` TINYINT NOT NULL DEFAULT 0,
  `approve_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `approve_time` DATETIME DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_edu_makeup_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `from_lesson_id` BIGINT UNSIGNED DEFAULT NULL,
  `to_lesson_id` BIGINT UNSIGNED DEFAULT NULL,
  `reason` VARCHAR(500) DEFAULT NULL,
  `apply_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `approve_status` TINYINT NOT NULL DEFAULT 0,
  `approve_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_edu_lesson_deduct_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `contract_id` BIGINT UNSIGNED DEFAULT NULL,
  `lesson_id` BIGINT UNSIGNED DEFAULT NULL,
  `change_type` VARCHAR(32) NOT NULL,
  `deduct_lessons` INT NOT NULL DEFAULT 0,
  `remaining_lessons` INT NOT NULL DEFAULT 0,
  `biz_ref_no` VARCHAR(64) DEFAULT NULL,
  `operator_id` BIGINT UNSIGNED DEFAULT NULL,
  `change_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/* ------------------------------
   6. 作品管理
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_art_artwork` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `artwork_no` VARCHAR(64) NOT NULL,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `lesson_id` BIGINT UNSIGNED DEFAULT NULL,
  `artwork_name` VARCHAR(128) DEFAULT NULL,
  `clay_type` VARCHAR(64) DEFAULT NULL,
  `size_spec` VARCHAR(128) DEFAULT NULL,
  `current_status` TINYINT NOT NULL DEFAULT 1,
  `photo_url` VARCHAR(500) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_art_artwork_no` (`artwork_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_art_glaze_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `artwork_id` BIGINT UNSIGNED NOT NULL,
  `glaze_color_code` VARCHAR(64) DEFAULT NULL,
  `glaze_color_name` VARCHAR(128) DEFAULT NULL,
  `glaze_date` DATE NOT NULL,
  `operator_id` BIGINT UNSIGNED DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_art_firing_batch` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `batch_no` VARCHAR(64) NOT NULL,
  `kiln_name` VARCHAR(128) DEFAULT NULL,
  `fire_type` VARCHAR(32) DEFAULT NULL,
  `schedule_time` DATETIME DEFAULT NULL,
  `start_time` DATETIME DEFAULT NULL,
  `end_time` DATETIME DEFAULT NULL,
  `target_temp` DECIMAL(8,2) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `operator_id` BIGINT UNSIGNED DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_art_firing_batch_no` (`batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_art_firing_batch_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `batch_id` BIGINT UNSIGNED NOT NULL,
  `artwork_id` BIGINT UNSIGNED NOT NULL,
  `position_no` VARCHAR(64) DEFAULT NULL,
  `result_status` TINYINT DEFAULT NULL,
  `result_note` VARCHAR(500) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_art_firing_batch_item` (`batch_id`, `artwork_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_art_pickup_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `artwork_id` BIGINT UNSIGNED NOT NULL,
  `notify_time` DATETIME DEFAULT NULL,
  `pickup_time` DATETIME DEFAULT NULL,
  `receiver_name` VARCHAR(64) DEFAULT NULL,
  `receiver_mobile` VARCHAR(32) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_art_damage_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `artwork_id` BIGINT UNSIGNED NOT NULL,
  `damage_time` DATETIME NOT NULL,
  `damage_level` VARCHAR(32) DEFAULT NULL,
  `damage_reason` VARCHAR(500) DEFAULT NULL,
  `compensation_plan` VARCHAR(500) DEFAULT NULL,
  `handled_by` BIGINT UNSIGNED DEFAULT NULL,
  `handled_time` DATETIME DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/* ------------------------------
   7. 库存与采购
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_inv_material` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `material_code` VARCHAR(64) NOT NULL,
  `material_name` VARCHAR(128) NOT NULL,
  `material_type` VARCHAR(64) DEFAULT NULL,
  `unit` VARCHAR(32) DEFAULT NULL,
  `spec` VARCHAR(128) DEFAULT NULL,
  `safe_stock` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_inv_material_code` (`material_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_inv_material_stock` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `material_id` BIGINT UNSIGNED NOT NULL,
  `warehouse_name` VARCHAR(128) NOT NULL,
  `qty_on_hand` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `qty_locked` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `last_in_time` DATETIME DEFAULT NULL,
  `last_out_time` DATETIME DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_inv_material_stock` (`material_id`, `warehouse_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_inv_material_txn` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `txn_no` VARCHAR(64) NOT NULL,
  `material_id` BIGINT UNSIGNED NOT NULL,
  `txn_type` VARCHAR(32) NOT NULL,
  `qty` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `unit_price` DECIMAL(12,2) DEFAULT NULL,
  `biz_ref_no` VARCHAR(64) DEFAULT NULL,
  `txn_time` DATETIME NOT NULL,
  `operator_id` BIGINT UNSIGNED DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_inv_material_txn_no` (`txn_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_inv_supplier` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `supplier_code` VARCHAR(64) NOT NULL,
  `supplier_name` VARCHAR(128) NOT NULL,
  `contact_name` VARCHAR(64) DEFAULT NULL,
  `contact_phone` VARCHAR(32) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_inv_supplier_code` (`supplier_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_inv_purchase_order` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `po_no` VARCHAR(64) NOT NULL,
  `supplier_id` BIGINT UNSIGNED NOT NULL,
  `order_date` DATE NOT NULL,
  `expected_arrival_date` DATE DEFAULT NULL,
  `total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `status` TINYINT NOT NULL DEFAULT 1,
  `buyer_id` BIGINT UNSIGNED DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_inv_purchase_order_no` (`po_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_inv_purchase_order_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `po_id` BIGINT UNSIGNED NOT NULL,
  `material_id` BIGINT UNSIGNED NOT NULL,
  `qty` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `unit_price` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `received_qty` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_inv_purchase_order_item` (`po_id`, `material_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/* ------------------------------
   8. 教师绩效
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_hr_teacher_profile` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `teacher_level` VARCHAR(32) DEFAULT NULL,
  `entry_date` DATE DEFAULT NULL,
  `base_salary` DECIMAL(12,2) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_hr_teacher_profile_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_hr_commission_rule` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `rule_name` VARCHAR(128) NOT NULL,
  `rule_type` VARCHAR(64) NOT NULL,
  `calc_formula` VARCHAR(1000) DEFAULT NULL,
  `effective_start` DATE NOT NULL,
  `effective_end` DATE DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_hr_teacher_payroll` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `payroll_month` CHAR(7) NOT NULL,
  `teacher_id` BIGINT UNSIGNED NOT NULL,
  `lesson_count` INT NOT NULL DEFAULT 0,
  `attendance_rate` DECIMAL(5,2) DEFAULT NULL,
  `commission_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `deduction_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `payable_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_hr_teacher_payroll` (`payroll_month`, `teacher_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/* ------------------------------
   9. 通知与反馈
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_msg_template` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `template_code` VARCHAR(64) NOT NULL,
  `template_name` VARCHAR(128) NOT NULL,
  `channel_type` VARCHAR(32) NOT NULL,
  `content` VARCHAR(2000) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_msg_template_code` (`template_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_msg_task` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `task_no` VARCHAR(64) NOT NULL,
  `template_id` BIGINT UNSIGNED DEFAULT NULL,
  `send_type` VARCHAR(32) NOT NULL,
  `scheduled_time` DATETIME DEFAULT NULL,
  `target_type` VARCHAR(64) DEFAULT NULL,
  `content_snapshot` VARCHAR(2000) DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `creator_id` BIGINT UNSIGNED DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_msg_task_no` (`task_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_msg_task_target` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `task_id` BIGINT UNSIGNED NOT NULL,
  `target_id` BIGINT UNSIGNED DEFAULT NULL,
  `target_mobile` VARCHAR(32) DEFAULT NULL,
  `send_status` TINYINT NOT NULL DEFAULT 0,
  `send_time` DATETIME DEFAULT NULL,
  `fail_reason` VARCHAR(500) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_msg_task_target` (`task_id`, `target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ty_crm_feedback` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED DEFAULT NULL,
  `student_id` BIGINT UNSIGNED DEFAULT NULL,
  `guardian_id` BIGINT UNSIGNED DEFAULT NULL,
  `feedback_type` VARCHAR(64) DEFAULT NULL,
  `content` VARCHAR(2000) DEFAULT NULL,
  `score` INT DEFAULT NULL,
  `feedback_time` DATETIME NOT NULL,
  `handler_id` BIGINT UNSIGNED DEFAULT NULL,
  `handle_status` TINYINT NOT NULL DEFAULT 0,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/* ------------------------------
   10. 统计报表
------------------------------ */
CREATE TABLE IF NOT EXISTS `ty_rpt_daily_kpi` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_id` BIGINT UNSIGNED NOT NULL,
  `stat_date` DATE NOT NULL,
  `new_leads` INT NOT NULL DEFAULT 0,
  `new_students` INT NOT NULL DEFAULT 0,
  `conversion_rate` DECIMAL(7,4) DEFAULT NULL,
  `class_fill_rate` DECIMAL(7,4) DEFAULT NULL,
  `attendance_rate` DECIMAL(7,4) DEFAULT NULL,
  `renewal_rate` DECIMAL(7,4) DEFAULT NULL,
  `revenue_amount` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  `cost_amount` DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ty_rpt_daily_kpi` (`campus_id`, `stat_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
